spring:
  #Database Configuration
  datasource:
    url: jdbc:postgresql://${DB_HOST:host.docker.internal}:5432/${DB_NAME:postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  application:
    name: cards
  jpa:
    properties:
      hibernate:
        default_schema: cards
    show-sql: true
    hibernate:
      ddl-auto: none
  data:
    rest:
      base-path: /api


#Swagger
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger
  api-docs:
    enabled: true
    path: /api-docs
#Server Configuration
server:
  port: 9000
  #servlet:
    #context-path: /api
