spring:
  #Database Configuration
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  application:
    name: cards
  jpa:
    properties:
      hibernate:
        default_schema: cards
    show-sql: true
    hibernate:
      ddl-auto: none
  data:
    rest:
      base-path: /api
  profiles:
    active: prod
  config:
    import: optional:configserver:http://localhost:8071/
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


management:
  endpoints:
    web:
      exposure:
        include: "*"
#Swagger
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger
  api-docs:
    enabled: true
    path: /api-docs
#Server Configuration
server:
  port: 9000
  #servlet:
    #context-path: /api

cards:
  message: "Welcome to Cards Local Microservice"
  contactDetails:
    name: "Aditya Local Cards"
    email: "Aditya@Local.com"
  onCallSupport:
    name: "Aditya Local"
    phone:
      - 5555555543
      - 5555555578
build:
  version: 2.0