version: "3.9"
services:
  accounts:
    image: adityaval317/accounts:s1
    container_name: accounts
    ports:
      - "8081:8081"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 700m
    networks:
      - backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
  loans:
    image: adityaval317/loans:s1
    container_name: loans
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 700m
    networks:
      - backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
  cards:
    image: adityaval317/cards:s1
    container_name: cards
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 700m
    networks:
      - backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

networks:
  backend:
    driver: bridge