spring:
  #Database Configuration
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  application:
    name: loans
  jpa:
    properties:
      hibernate:
        default_schema: loans
    show-sql: true
    hibernate:
      ddl-auto: none
  data:
    rest:
      base-path: /api
  config:
    import: ${SPRING_CONFIG_IMPORT:configserver:http://localhost:8071/}
  profiles:
    active: prod
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  info:
    env:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      access: unrestricted
  metrics:
    tags:
      application: ${spring.application.name}

#Eureka Configuration
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://${SPRING_EUREKA_SERVER:localhost}:8070/eureka

#Info Configuration
info:
  app:
    name: loans
    description: Loans Microservice
    version: 1.0.0


#Swagger
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger
  api-docs:
    enabled: true
    path: /api-docs
#Server Configuration
server:
  port: 8090
  #servlet:
    #context-path: /api

build:
  version: 1.0

loans:
  message: "Welcome to Loans Microservice"
  contactDetails:
    name: "Aditya"
    email: "Aditya@qa.com"
  onCallSupport:
    name: "Aditya"
    phone:
      - 5555555543
      - 5555555578

logging:
  level:
    com:
      aditya:
        microservices:
          loans: DEBUG
  pattern:
    level: "%5p[${spring.application.name}, %X{trace_id}, %X{span_id}] %d{yyyy-MM-dd HH:mm:ss.SSS} - %m%n"