spring:
  #Database Configuration
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  application:
    name: loans
  jpa:
    properties:
      hibernate:
        default_schema: loans
    show-sql: true
    hibernate:
      ddl-auto: none
  data:
    rest:
      base-path: /api
  config:
    import: ${SPRING_CONFIG_IMPORT:configserver:http://localhost:8071/}
  profiles:
    active: prod
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
#Swagger
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger
  api-docs:
    enabled: true
    path: /api-docs
#Server Configuration
server:
  port: 8090
  #servlet:
    #context-path: /api

build:
  version: 1.0

loans:
  message: "Welcome to Loans Microservice"
  contactDetails:
    name: "Aditya"
    email: "Aditya@qa.com"
  onCallSupport:
    name: "Aditya"
    phone:
      - 5555555543
      - 5555555578