spring:
  #Database Configuration
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  application:
    name: accounts
  jpa:
    properties:
      hibernate:
        default_schema: accounts
    show-sql: true
    hibernate:
      ddl-auto: none
  data:
    rest:
      base-path: /api
  config:
    import:
      - application_qa.yml
      - application_prod.yml
  profiles:
    active: qa
#Swagger
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger
  api-docs:
    enabled: true
    path: /api-docs
#Server Configuration
server:
  port: 8081
  #servlet:
    #context-path: /api

build:
  version: 3.0

accounts:
  message: "Welcome to Accounts Microservice"
  contactDetails:
    name: Aditya
    email: 5kKbY@example.com
  onCallSupport:
    name: Aditya
    phone:
      - 5555555555
      - 5555555556
