spring:
  #Database Configuration
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  application:
    name: accounts
  jpa:
    properties:
      hibernate:
        default_schema: accounts
    show-sql: true
    hibernate:
      ddl-auto: none
  data:
    rest:
      base-path: /api
  profiles:
    active: prod
  config:
    import: ${SPRING_CONFIG_IMPORT:configserver:http://localhost:8071/}
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
    function:
      definition: updateCommunication
    stream:
      binders:
        kafka:
          type: kafka
        rabbit:
          type: rabbit
      bindings:
        updateCommunication-in-0:
          destination: communication-sent
          group: ${spring.application.name}
          binder: rabbit
        sendCommunication-out-0:
          destination: send-communication
          binder: rabbit
        accountCreated-out-0:
          destination: account-created
          binder: kafka
      default-binder: kafka
      kafka:
        binder:
          brokers:
            - localhost:9092
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10s
#Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  info:
    env:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      access: unrestricted
  metrics:
    tags:
      application: ${spring.application.name}

#Swagger
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger
  api-docs:
    enabled: true
    path: /api-docs
#Server Configuration
server:
  port: 8081
  #servlet:
    #context-path: /api


#Eureka Configuration
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://${SPRING_EUREKA_SERVER:localhost}:8070/eureka

#Info Configuration
info:
  app:
    name: accounts
    description: Accounts Microservice
    version: 1.0.0

build:
  version: 3.0

accounts:
  message: "Welcome to Accounts Microservice"
  contactDetails:
    name: Aditya
    email: 5kKbY@example.com
  onCallSupport:
    name: Aditya
    phone:
      - 5555555555
      - 5555555556

logging:
  level:
    com:
      aditya:
        microservices:
          accounts: DEBUG
  pattern:
    level: "%5p[${spring.application.name}, %X{trace_id}, %X{span_id}] %d{yyyy-MM-dd HH:mm:ss.SSS} - %m%n"

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      permittedNumberOfCallsInHalfOpenState: 3
      waitDurationInOpenState: 10000
      failureRateThreshold: 50
      eventConsumerBufferSize: 10


resilience4j.retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 1000ms
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        ignoreExceptions:
          - java.lang.NullPointerException
        retryExceptions:
          - java.lang.RuntimeException
          - java.util.concurrent.TimeoutException

resilience4j.ratelimiter:
  configs:
    default:
      timeoutDuration: 1000
      limitRefreshPeriod: 5000
      limitForPeriod: 10
