spring:
  application:
    name: configserver
#  config:
#    import: optional:configserver:${user.home}/spring-cloud-config
  profiles:
    #active: native
    active: git
  cloud:
    config:
      server:
        #native:
          #search-locations: classpath:/config
          #search-locations: file:///C://DEV//Workspace//Spring//microservices//config-server//src//main//resources
        git:
          uri: https://github.com/adityaval317/config.git
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: 5672
    username: guest
    password: guest


encrypt:
  key: 45D81EC1EF61DF9AD8D3E5BB397F9
server:
  port: 8071
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  pattern:
    level: "%5p[${spring.application.name}, %X{trace_id}, %X{span_id}] %d{yyyy-MM-dd HH:mm:ss.SSS} - %m%n"

