cards:
  message: "Welcome to Cards QA Microservice"
  contactDetails:
    name: "Aditya QA Cards"
    email: "Aditya@qa.com"
  onCallSupport:
    name: "Aditya QA"
    phone:
      - 5555555543
      - 5555555578
build:
  version: 2.0